### ISSUE TITLE
NotificationCenter shows pending guesses from hunts you don't operate for

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#1353]
We saw an issue this weekend where someone was an operator for hunt A but not hunt B, but was pushed pending guesses for hunt B.

**Comment by ebroder** [comment]
This issue has been linked to an error in Bugsnag
[**Error** in **Guesses.methods.setState**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/63c1c894f494830008b66920?event_id=63c1c89400aacd35c7420000&i=gh&m=li)

**Comment by zarvox** [comment]
I think I figured out how this was happening.  There's nothing wrong with `pendingGuesses`, but these is a problem with `NotificationCenter` where it doesn't filter down to only guesses from hunts for which you are an operator, and it is possible to wind up with all guesses for a particular puzzle from a PuzzlePage.  So if you're an operator for hunt A, but not hunt B, when you submit a guess for a puzzle in hunt B, you'll see the guess for that puzzle in the NotificationCenter and have action buttons that don't work (because you're not actually an operator for that hunt, and the serverside enforces this correctly).
