### ISSUE TITLE
Server-side errors involving deleted puzzles

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#1370]
We saw a few issues in server-side methods related to deleted puzzles. It seems like `findOneAllowingDeleted` may not be working correctly, although I don't see any obvious issues.

* Editing a deleted puzzle throws an error
  
  ```
  Error Unknown puzzle id [404] 
      imports/server/methods/updatePuzzle.ts:35:13 
      /built_app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
      /built_app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12 Function.Promise.await
      imports/methods/TypedMethod.ts:104:13 
      /built_app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40 
  ```
* Undeleting a puzzle throws an error
   
  ```
   Error Unknown puzzle id [404] 
       imports/server/methods/undestroyPuzzle.ts:25:13 
   ```

**Comment by ebroder** [comment]
This issue has been linked to an error in Bugsnag
[**Error** in **Puzzles.methods.update**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/63c1c81ab58704000938fe59?event_id=63c1c81a00aac3d0212e0000&i=gh&m=li)

**Comment by ebroder** [comment]
This issue has been linked to an error in Bugsnag
[**Error** in **Puzzles.methods.undestroy**](https://app.bugsnag.com/death-and-mayhem/jolly-roger/errors/63c1c4a7782975000821f014?event_id=63c492a300aad17c54b20000&i=gh&m=li)

**Comment by ebroder** [comment]
Ugh. I think I understand what's happening here. These bugs were introduced when we switched to using async database calls. The way that the standard async methods on `Mongo.Collection` are [defined](https://github.com/meteor/meteor/blob/2241e617986e90c73f8e4d4f060fba4ac978b86d/packages/mongo/collection.js#L919-L924):

```
ASYNC_COLLECTION_METHODS.forEach(methodName => {
  const methodNameAsync = getAsyncMethodName(methodName);
  Mongo.Collection.prototype[methodNameAsync] = function(...args) {
    return Promise.resolve(this[methodName](...args));
  };
});
```

means that `findOneAllowingDeleted` calls `findOneAsync` which calls `findOne`, but it calls _our_ implementation of `findOne` rather than the implementation on `Mongo.Collection`, which means that we inject the `{deleted: false}` query term.

I'm honestly not sure how we can work around this with Meteor's current async implementation. I'm tempted to define `findOneDeletedAsync` and `findOneAllowingDeletedAsync` to call their non-async versions, the same as Meteor does, at least until Meteor switches to async-by-default.

**Comment by zarvox** [comment]
A few additional options, none of them great:

* slightly cursed but maybe "fine": we could replace Meteor's async collection method implementations with ones that call the method name from the prototype instead of our monkeypatch, since we already override them.
* not-cursed but ugly: avoid monkeypatching `find()` or `findOne()` in the `Base` model, define different methods that do what we want, and migrate all our callsites.  Slightly awkward since `find()` is the mongo-given name for the operation, and at this point we'd probably have to lint-ban `find()` to avoid accidentally getting the allowing-deleted behavior when we didn't mean to ask for it.  This is actually probably the most stable, if annoying, solution.
* very cursed: we could keep collection-level state that tracks find() enters and exits and knows whether the upper-level call expects a call back from Meteor, and adjust our query injection accordingly.  
* extremely cursed: instead of keeping state, we could dump a stacktrace on each call, walk up the stack, and determine if the nearest model call was coming from app code or Meteor, and adjust our query injection accordingly

Okay yeah I'm fine with your suggestion -- all of these options except "avoid monkeypatching `find()` are going to require we fix our workaround when Meteor updates, which I dislike (it's easy to forget we need to do this, especially since we don't test deleted stuff much), but we were probably going to ~have to do that anyway.  The ugly option above behave consistently and predictably, but is slightly more annoying to type and risks errors from inconsistency in usage.

**Comment by ebroder** [comment]
We can pretty easily add a test that will fail if the behavior changes, so we catch it on upgrade
