### ISSUE TITLE
Make sure user-provided text has `word-break: break-word`

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#185]
We should double-check anywhere that we take user-provided output without a length limit and render it, and make sure those elements have `word-break: break-word` set in their CSS so that users can't break the layout with overflows.

This definitely includes chat messages and submitted answers. We may want to include operator-managed text like announcements and puzzle titles.

**Comment by zarvox** [comment]
There are actually two CSS properties we want to think about here:

* [`overflow-wrap: break-word`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) AKA `word-wrap: break-word`
* `word-break: break-word` is nonstandard, so don't use it.  [`word-break: break-all`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) will insert the newline at the first character that would overflow the container, even if wrapping at word boundaries would prevent needing to break mid-word at all, which generally looks worse than wrapping at word boundaries.

There are relatively few places where I think we'd prefer `word-break: break-all` to just having `overflow-wrap: break-word`; namely, for guesses (from which we usually strip whitespace entirely).  We already use `word-break: break-all` everywhere we render a guess, I think, with the possible exception of the answer queue notifications.

I basically trust operators to make reasonable decisions with respect to hunt names and puzzle titles, and we already [break puzzle titles](https://github.com/deathandmayhem/jolly-roger/blob/master/client/stylesheets/puzzle.scss#L49) and [puzzle answers](https://github.com/deathandmayhem/jolly-roger/blob/master/client/stylesheets/puzzle.scss#L69-L70).  This leaves:

* Display names in chat, answer queue submissions, and announcements
* Chat messages
* Tags

I'm inclined to say that if people want to make lousy tag names, they can live with it, or people will delete them instead and make more usable tag names.

For display names and chat messages, we already use [`word-wrap: break-word`](https://github.com/deathandmayhem/jolly-roger/blob/master/client/stylesheets/puzzle.scss#L280) (which cascades to everything in that div)

This leaves display names in answer queue submissions and announcements.  I'm okay with requiring operators to have reasonable display names, since they're the only folk who can create announcements.

This leaves the answer queue & answer queue notifications.  I'll make a PR for these.
