### ISSUE TITLE
Consider dropping chat font size

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#214]
We got some user requests to drop the font size on the chat bar (it's currently inheriting the body default of 14px). 12px feels a little small to me, but 13px feels very plausible.

**Comment by zarvox** [comment]
Additional context from chat was that the primary goal here was to be able to see more history at once, 

I fiddled around with this a bit and I have some thoughts:

* we should definitely shrink the timestamp to at most 12px, regardless of what we do with anything else the rest of things.  It's not particularly important information, and the large size is somewhat distracting.  Maybe we should make it grey instead of black too.
* we can probably steal 2px back from the gutter (6px -> 4px)
* we should try to focus on readability, potentially at the expense of information density
* readability is generally better with more spaced-out text and larger text
* our chat window text currently looks big compared to the google sheets, which appears to default to 10pt (~13px) Courier New.  Matching, or at least getting close, would likely improve general usability, since people can zoom their browser view to an acceptable size for both at once.

So given that, there's a few options:

* Keep things as-is (14px text, 10/7th line-height)
* Reduce font size (e.g. 13px), keep or increase line-height to maximize readability
* Increase font size (e.g. 15px, which is what Slack uses), drop line-height from 10/7ths to 1.2 or 1.3

Out of these, when I was experimenting, I found larger font sizes easier to read more quickly, but I found the general appearance of the smaller font + larger line-height more optically appealing.  I think I'm fairly swayed by the argument that we should avoid being particularly different from the google sheets text.

Another approach we could try orthogonal to `font-size` and `line-height` (though I'm wary of trying to implement it at the last minute) is eliding the author and timestamp line if the author is the same as the previous message (and the timestamp is close enough?).

**Comment by zarvox** [comment]
Okay I think I talked myself out of shrinking the chat font size and instead increasing the font size of the template google doc so that sizes are more consistent across all things, and then letting people use their browser's zoom feature to make things as large or small as they're comfortable reading and packing content.

I'll still do the "shrink the timestamp" and "grab pixels from the gutter" and "make the background white not grey" changes here though

**Comment by grantaelliott** [comment]
Makes sense.  If you do end up changing the gutters, please try to adjust the padding on the chat textarea and the related puzzles to match (well, off by 1 for the text area because of the border).

In the long term, I think you're right about hiding unnecessary headers.

**Comment by grantaelliott** [comment]
This was addressed by #222 and @223.
