### ISSUE TITLE
Overhaul emoji support

### ISSUE THREAD

**Issue by zarvox** [deathandmayhem/jolly-roger#291]
We should probably come up with a uniform emoji support philosophy.

We probably want to figure out what fields should support emoji, and with what font face(s), in what order of preference, and how.  For instance, right now, whitespace in answers are getting emoji font treatment, which makes them wide and blocky.  I believe the same may be true of numerals in answer blocks.  Let's audit all of that.

We should also figure out how to make this work without enabling XSS.

We may wish to support github/slack-style colon-codes for emoji substitution/emoji picking.

**Comment by zarvox** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range seems like it might help us out here with the immediate issue of "whitespace gets emoji-width spacing under `.answer`" -- we can declare an `@font-face` naming a new `font-family`, then only apply it to particular unicode ranges (e.g. U+1????).

Then we can apply those `font-family`s to `.answer`, and since they won't cover U+20, they'll fall back to monospace.

**Comment by ebroder** [comment]
Now that it's no longer the middle of hunt, I do want to spend some time thinking about what the right behavior here is, and I wonder if it's worth thinking about it independently for answers vs. chat.

For chat, it feels like we should try to find something wholistic that handles Slack-style formatting (`*`, `_`, `>`, `` ` ``, etc., but also emoji). For answers, my intuition is that I still would mildly prefer to plug in twemoji, so that we get cross-platform consistency, rather than continue to fight with native font rendering.

**Comment by zarvox** [comment]
This is done!  We have a standard set of fonts, and specify specific unicode ranges for which to prioritize the use of native emoji fonts, and we apply that throughout the app.
