### ISSUE TITLE
Add chat notifications based on username mentions

### ISSUE THREAD

**Issue by grantaelliott** [deathandmayhem/jolly-roger#337]
In the past, the Slack firehose channel allowed you to receive a notification when you were mentioned by username. Discord's ability to set custom alerting logic is somewhat more limited, but even if it weren't, it would be nice to offer this within Jolly Roger itself.

Specifically, it would be good if you could receive an alert that your name has been called out in chat (likely using @). Since we don't have usernames, this would probably require a dropdown to search for the user (similar to the UI used for tag entry). It may also make sense to add a handle field to user profiles, since we have many users as well known by their handles as by their names.

**Comment by zarvox** [comment]
This is a solid feature spec, thanks for filing!

I think this will also need some nontrivial serverside support, since I think it'd be unsupportable load-wise to have every client watching every puzzles chatmessages all the time (and that would blow per-tab RAM usage through the ceiling).

If we do wind up doing this, we probably want some plan around load-testing or deferred work queue, because I can see the fanout of checking every user's pingwords against every chat message sent adding up to a fair bit of CPU/DB load.

This probably also *ought* to take ACLs into consideration?  Don't want people getting notifications about puzzles in hunts they don't belong to.

Were you anticipating these being the in-tab notifications that we have for general announcements/guess queue for operators, or desktop notifications?

**Comment by grantaelliott** [comment]
I'm assuming these would be the same in-page notifications we have for announcements and operator requests. Supporting desktop notifications as a fallback (when not connected) would be very nice, with the big caveat that iOS still doesn't have support.

**Comment by ebroder** [comment]
I'm going to rework this ticket to reflect support for configurable keywords. I think there's still an open issue around username notification. Here's the original text of the issue from before my edits:

> In the past, it's been possible for users to set up notifications in Slack's firehose channel for keywords of interest to them or their own names. This may be possible in Discord as well, but even if so, it would be nice to offer this within Jolly Roger itself. The existence of this feature would also eliminate one of the arguments in favor of maintaining a firehose channel (or even of mirroring chat entirely).
> 
> I propose two types of such notifications, each delivered with a link back the corresponding Jolly Roger page.
> 
> * Alert that your name has been called out in chat (likely using @). Since we don't have usernames, this would probably require a dropdown to search for the user (similar to the UI used for tag entry). It may also make sense to add a handle field to user profiles, since we have many users as well known by their handles as by their names.
> * Alert that one of your configured keywords has been mentioned in chat. A user's list of notifiable keywords would be part of their profile. This would be particularly useful for users with very specialized skills (such as uncommon foreign languages) or interest in particular puzzle types.

**Comment by ebroder** [comment]
For what it's worth, I did find these tutorials on building autocomplete support into a text entry field:

* https://css-tricks.com/so-you-want-to-build-an-mention-autocomplete-feature/
* https://www.algolia.com/doc/ui-libraries/autocomplete/solutions/rich-text-box-with-mentions-and-hashtags/
