### ISSUE TITLE
We should have a functional "delete puzzle" button

### ISSUE THREAD

**Issue by zarvox** [deathandmayhem/jolly-roger#425]
Hide it behind like three layers of indirection for safety and make it only available to operators, but "oops two people created a puzzle entry at once" or "we already had a stub for that meta, and then made another one" should not require admin-in-js-console to rectify.

**Comment by ebroder** [comment]
I think there are an assortment of things we can potentially do to make this more useful:

- Have a useful error page if you go to the URL of a deleted puzzle or if you have it open when it's deleted (right now I think you just get a blank 404)
- Possibly allow specifying a "go here instead" link
- Showing read-only chat history
- Giving people a link to the Google Sheet for the puzzle so that they can recover/migrate data (we could potentially revoke permissions and make it view-only so we don't have to worry about people continuing to do work there, although we might have to worry about Google Drive rate limits)
- Have an "undelete" button for operators
