### ISSUE TITLE
Cosmetic Updates to Individual Hunter Profiles

### ISSUE THREAD

**Issue by flipdog** [deathandmayhem/jolly-roger#550]
This is very low-priority, but as an operator I have a few cosmetic requests to the profile pages for individual hunters. This is specific to the view for operators, but I'm assuming that some of these elements could also be relevant to the non-operator profile views. (I'm not 100% sure what elements a non-operator can even see)

1. Increase Spacing of Elements - In particular, the "make operator" button has no spacing from the Gravatar element below it and looks weird, but I think generally the elements could be spaced out a touch more.
2. Fix Gravatars - For users that do have icons on gravatar, the avatars on their profile page still don't show, and you get the default gravatar element. We should probably either make them load correctly or decide they don't matter and just remove that element entirely.
3. Include information elements for empty fields - if a user does not have a linked Discord or listed phone number, it would be nice to still include an empty line for that. I'm imagining "Phone Number: NONE ENTERED" and "NO DISCORD PROFILE LINKED". This would make the profiles more consistent in layout, and make it more obvious to a new or infrequent operator what information to expect.
4. Hyperlink Discord Profile to DM - As an operator, the most common reason I look someone up is because they're doing something confusing on a particular puzzle page. A quicklink to be able to send them a DM in Discord would be a quality of life improvement.
5. Add a "last time active" information element - Again, when looking someone up as an operator, it's often because I'm confused about something they've done or are doing. Being able to quickly see things like "this person hasn't logged in at all this year" or "this person hasn't had any activity in 4 hours" gives me a sense of what's up. I don't know how much we're tracking that activity at all, so this may be a tough request, but at a minimum "last login" is more information than we have now.
6. Add a list of Hunts this hunter was in - It's nice to know at a glance a person's level of experience or involvement with the team, so seeing that somebody has been with us for several hunts, or isn't added to this year's hunt, or was with us a couple years ago but not last year, can be informative.

**Comment by zarvox** [comment]
This is great input; thanks for writing it up!

> Increase Spacing of Elements

Yeah, this whole page definitely deserves a cosmetic rework.  I think it's mostly just operators/admins that look at other people's profiles, but we could definitely make things look tidier/more tabular/with better grid lines.

> Fix Gravatars

I'm inclined to just remove Gravatar entirely and just show discord avatars (in the discord block) if the user has linked their account.  Very few people have set up Gravatars in the first place, and it seems to not see much new adoption.  (In an ideal world, we might also show Google avatars if the user has a linked Google account, but we didn't and still don't record people's Google account IDs when people link them, so we have no way to retrieve them without making everyone re-link Google accounts.)

> Include information for empty fields

This should be super straightforward to implement, and yeah, I like that the suggested design helps indicate what information is possible rather than relying on humans to know what to expect and notice the absence of data.

> Hyperlink Discord Profile to DM

This should also be quite easy -- I think it's just  `https://discord.com/users/${discordUserId}`

> Add a "last time active" information element

I don't think we currently track user activity in the way you're hoping.  There's a `lastLogin` field we stuff on Meteor.user but that only gets sent when you do the password-based login, not on like pageview or navigation or anything like that.  And resume tokens (the "you're already logged in" cookie equivalent) are pretty long-lived.  This one might take a little more effort.

> Add a list of Hunts this hunter was in

We store this data to `Meteor.User`, so this too should be pretty straightforward to implement.  It might be a little confusing data-wise when people swap from one email address to another, producing additional accounts (there's several folks with at least `@mit.edu` and `@gmail.com` addresses, and some folks also have a bonus `@alum.mit.edu` address), but in those cases all of the relevant profiles will be in the all-users page, so it should be clear that there's multiple accounts at least.

**Comment by flipdog** [comment]
On the last point - funny enough, I was also going to put in an issue suggesting that at some point we will want to add a "merge user" functionality for operators/admins (although that also gets into the question of whether we want operators to continue being global and how much admin power they should have). Now that JR's been around a bit, I'm starting to think a little longer term across multiple hunts, and I think that being able to merge users will end up having added value for us in terms of keeping things clean.

**Comment by ebroder** [comment]
I moved the point about last activity time into #569, and I think that otherwise this issue is resolved. (re: merging accounts, we're tracking that at #296)
