### ISSUE TITLE
Rework permissions to be scoped per-hunt

### ISSUE THREAD

**Issue by ebroder** [deathandmayhem/jolly-roger#618]
Right now, the operator permission is a global permission. This means that anyone who has ever been an operator on a Jolly Roger instance has those permissions in perpetuity, and it's difficult to use a single instance of Jolly Roger among different groups (who may not all use the same set of operators).

We should fix this by making roles that are scoped to an individual hunt. These would not replace global roles - at the very least, the `admin` role must remain global (it doesn't make sense to only have the admin role on a single hunt)

## Data model

Currently roles are tracked as a property of the `Meteor.User` type:

```typescript
  roles?: string[];
```

Instead, we change them to have an additional scope, tracked as a record type:

```typescript
type Scope = string;
const GLOBAL_SCOPE = '__GLOBAL__';

type Permission = string;
[...]
  roles?: Record<Scope, Permission[]>
```

In practice, the `admin` role would be the only global role, and the `operator` role would be the only hunt-scoped role, but nothing structurally prevents that. For the data migration, anyone who has the currently global `operator` role will have that role migrated onto all hunts of which they are currently members.

## "Active operator"

Today `"inactiveOperator"` is a separate role from `"operator"`. An `inactiveOperator` only has permissions to make themselves an operator (i.e. they can add themselves to the `operator` role). This was originally done when we retrofitted the ability to enable/disable operating mode, because all of the operator UI elements conditionalize on having a permission, not on having a particular role, and taking away the `operator` mode was the most expedient way to make all of them disappear.

As part of this change, make operator active status a client-side property, stored in `localStorage` and scoped per-hunt. Operators always have the operator role, and at each permission check we look at `localStorage` to decide whether to show the UI elements. To make it easier to toggle activeness, make a UI element on the puzzle list page, next to the add puzzle button.

Given that the UI element would be on an individual hunt page and not global, my preference is to make the activeness a per-hunt property.

This would address both #599 and #212.

## Future work

In the long term, it would be great if anyone with a Jolly Roger account could create a new hunt, of which they would be the sole operator. However, that is explicitly out of scope for this issue. One challenge to remember in supporting this is risk of a confused deputy with external integrations. Jolly Roger is an admin on Discord servers it inhabits by default, which is more role power than we want.

As an intermediate fix, I'd propose disabling all external integrations (mailing lists, Discord) for new hunts created by non-admins. If a non-admin operator edits a hunt, we preserve but do not allow modification of any external integration configuration. If necessary, an admin can always edit the hunt and add those integrations. In the future, we should make Discord guild configuration a per-hunt property so that we can make it accessible. We also need to make the hunt list display sensibly if you can only edit some but not all hunts (e.g. make sure the alignment is reasonable).

**Comment by zarvox** [comment]
I think this looks great, and I'm 100% in favor of everything in the first two sections.  I'm also enthusiastic about the goal of the third section, but think that we should consider this an intermediate milestone towards that goal, and separate out "non-admin-created-hunts" as a separate feature in the fullness of time, since it'll probably impact a good deal of flows and interactions, even if none of them feel particularly visible to most participants.

### Data model

:shipit: 

### Active operator

For the UI in "Active operator" -- just to be clear, the default behavior if no value is present in localStorage for a particular hunt should be that if the use has operator powers, they see operator's UI.  There's a couple of flows that are much smoother with this parity:

* When promoting a participant into an operator, only the operator needs to take action for the new operator to see the proper operator UI.
* When creating or joining a new hunt, operators will see operator UI rather than requiring an additional step before being able to make use of operator UI.

So we should make sure that whatever setting we put in localStorage is phrased as something like "hideOperatorActionsOnPuzzlePage"

### Third-party integrations

I agree that these would be sensitive, and perhaps best to just try to avoid supporting for now.

We could also take this opportunity and overall goal as an opportunity to rethink the nature of how some of our external integrations are configured.  For instance, instead of having server-global settings for doc templates, Drive folder and server account, we could have an approach where when configuring a hunt, the hunt-creating operator configures credentials for the backend to use for that hunt.  Then, instead of having a single gdrive client refresher, we'd have one-per-hunt, and all serverside actions on drive would need to look up the hunt and use the credentials from that Hunt.  This would definitely increase the surface area of credentials that we'd need to store and retrieve, and perhaps we'd want to store these values separately from the actual `Hunt` objects themselves to ensure we don't accidentally publish them to clients, but I see no fundamental reason why we couldn't take this alternate approach, and in our case we could continue to use our current google account in production as the "data owner" that provides the Drive folder and the ability to create documents within that folder to the hunt config.  Splitting out the server-wide "identity/code owner" from the per-hunt "data/access owner" feels appropriate.

Discord guild configuration feels somewhat similar.  I could imagine an additional step in the Hunt-provisioning flow where the user creating the Hunt would create an OAuth delegation to the bot (probably for a smaller set of permissions than admin, as you've noted), and then the UI for hunt configuration could allow you to select from among [no guild, the guild currently configured, the list of guilds that *your* user account has granted the bot access].  There will be implications on the backend around `DiscordCache` data and its visibility; I think based on the structure of Discord's bot integrations we'd still need only one bot account & connection to Discord itself, but we'd have to be much more careful about what data we publish where.

As for mailinglists: I think in practice, besides our current production instance, there are 0 deployments that make use of the blanche mailinglist integration, and if we're being honest, probably close to 0 potential future jolly-roger server administrators who would pick blanche for new future use?  The plan for making it so only an admin can add that integration seems adequate to me.  I would not be sad if we eventually retired the blanche integration in favor of some other mailinglist integration (though I'm also not excited about writing a new one and migrating all our users either, and we definitely need **a** mailinglist for our team somewhere, and I'm not excited about requiring Google accounts for participants, but I'm also not excited about "run your own mailinglist software" so I don't have a great alternative).

**Comment by ebroder** [comment]
Yeah reasonable. I've reworked "non-admin-created-hunts" as a future goal.

+1 to enabled by default. I think that works well with the setting being hunt-scoped. For what it's worth, my plan was to pull in [use-persisted-state](https://github.com/donavon/use-persisted-state), which I've been eyeing for a while for our interfaces into `localStorage`. It automatically sets up the various event handlers to update both across windows and across multiple invocations of the same `localStorage` record, and JSON encodes and decodes state before writing it out to `localStorage` (which is well-suited to a more structured representation).
